// Enum of all methods transfered over RPC between ui & core
export enum RpcAction {
    REMOVE_THEME_STYLE = "REMOVE_THEME_STYLE",
    SYNC_THEME_STYLES = "SYNC_THEME_STYLES",
    SYNC_THEME_STYLE = "SYNC_THEME_STYLE",
    GET_RAW_STYLES = "GET_RAW_STYLES",
    REDRAW_FRAME = "REDRAW_FRAME",

    GET_CURRENT_SELECTIONS = "GET_CURRENT_SELECTIONS",
    ON_SELECTION_CHANGE = "ON_SELECTION_CHANGE",

    MERGE_SERIALIZED_THEME_WITH_CURRENT = "MERGE_SERIALIZED_THEME_WITH_CURRENT",
    IMPORT_STYLE_FROM_FRAME_TO_THEME = "IMPORT_STYLE_FROM_FRAME_TO_THEME",
    SERIALIZE_CURRENT_PAGE_THEME = "SERIALIZE_CURRENT_PAGE_THEME",
    SELECT_ALL_FRAMES_BY_STYLE = "SELECT_ALL_FRAMES_BY_STYLE",
    REMOVE_THEME_FROM_LIBRARY = "REMOVE_THEME_FROM_LIBRARY",
    RENAME_LIBRARY_THEME = "RENAME_LIBRARY_THEME",
    ADD_TO_SELECTIONS = "ADD_TO_SELECTIONS",
    SET_LIBRARY_THEME = "SET_LIBRARY_THEME",
    GET_LIBRARY = "GET_LIBRARY",
}
